sudo: false
language: ruby
node_js:
- '8'
branches:
  only:
  - master
  - gh-pages
  - _get_build_working
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- bundler add jekyll
- bundler add jekyll-tidy
- npm install dev
script:
- jekyll build -d _site
- npm run coverage
after_success:
- npm run coveralls
