destination: _site
exclude: ['node_modules', 'jest.config.js', 'package.json', 'package-lock.json', 'coverage']

plugins:
  - jekyll-tidy

collections:
  quizes:
    output: true

defaults:
  - scope:
      path: ""
      type: "quizes"
    values:
      layout: quiz

key_width: 32

white_height: 190

# split black_keys to distinguish # and b option, total height = 126
black_height: 63

default_keyboard: 4

low_keyboard: 2

high_keyboard: 6
