destination: _site
exclude: ['node_modules', 'jest.config.js', 'package.json', 'package-lock.json']

plugins:
  - jekyll-tidy

collections:
  quizes:
    output: true

defaults:
  - scope:
      path: ""
      type: "quizes"
    values:
      layout: quiz